language: go

# go1.13 is the minimum required version because of os.UserHomeDir
go: [ "1.13", "1.x", "master" ]

go_import_path: github.com/rillig/gobco

install: go get -d -t -v ./...

before_script: go generate -x ./...

# don't test the subpackage since both samples and templates
# are not meaningfully testable on their own.
script: go test -coverprofile=coverage.txt -covermode=count

after_success: bash <(curl -s https://codecov.io/bash)
