# See https://docs.travis-ci.com/user/languages/go/#go-modules

language: go

env: GO111MODULE=on

# go1.16 is the minimum required version because of go:embed.
go: [ "1.16", "1.x" ]

go_import_path: github.com/rillig/gobco

install: go get -d -t -v ./...

# Don't test the subpackages since both ./sample and ./templates
# are not meaningfully testable on their own.
script:
  - go test -coverprofile=coverage.txt -covermode=count .
  - go install
  - gobco || true

after_success: bash <(curl -s https://codecov.io/bash)
