# See https://docs.travis-ci.com/user/languages/go/#go-modules

language: go

env: GO111MODULE=on

# go1.13 is the minimum required version because of os.UserHomeDir
go: [ "1.13", "1.x" ]

go_import_path: github.com/rillig/gobco

install: go get -d -t -v ./...

before_script: go generate -x ./...

# don't test the subpackage since both samples and templates
# are not meaningfully testable on their own.
script:
  - go test -coverprofile=coverage.txt -covermode=count .
  - go install
  - gobco || true

after_success: bash <(curl -s https://codecov.io/bash)
