# See https://docs.travis-ci.com/user/languages/go/#go-modules

language: go

env:
  - GO111MODULE=on

# go1.16 is the minimum required version because of go:embed.
go:
  - "1.16"
  - "1.x"

go_import_path: github.com/rillig/gobco

install:
  - go get -d -t -v ./...

# Don't test the subpackages since the templates in ./templates
# are not meaningfully testable on their own.
script:
  - go test -coverprofile=coverage.txt -covermode=count .
  - go test ./testdata/instrumenter
  - go install
  - gobco .
  - gobco ./testdata/instrumenter

after_success:
  - bash <(curl -s https://codecov.io/bash)
